### PR TITLE
Fully deprecate and remove building of v1 registry

### LINKED ISSUE #835: Hard deprecate ETS registry
Version of 2 of the registry that replaced the ETS based registry was introduced three years ago. The new version was needed to fix scalability issues with the old registry. The ETS registry is a single file and has to be rebuilt on every package publish. The ETS file has now grown to 12MB and rebuilding it is by far to be the slowest part of processing a package publish.

It is hard for us to gauge the usage of the old registry and even harder to inform users to stop using it and upgrade their installations and services. The plan is to stop updating the ETS file but continue to host it to avoid breaking old installations.

The first step is to update the ETS registry asynchronously. This means that the registry may not updated after the `/api/publish` endpoint returns, instead it will be available a few seconds later. This means `/api/publish` will become much quicker and should not affect users much. Second step is to update it on a timer (for example every six hours) instead of on publish, and then grow this timer.

During this time we will look for user reports and help them migrate to newer versions of their package managers. And for users accessing the registry directly we will help them migrate to the new format. And eventually we will stop updating the ETS registry completely.

### PR DESCRIPTION
**Pull request by ericmj**
Closes #835.

### CODE REVIEW

**Review by wesleimp — APPROVED** [review]
LGTM 👌🏼

**Review by wojtekmach — APPROVED** [review]
LGTM!

There's a WG meeting this Friday so let's wait with shipping this at least until after that.

**Comment by ericmj** [comment]
> There's a WG meeting this Friday so let's wait with shipping this at least until after that.

Sounds good. Some more notes on the timeline of the v1 deprecation for background:

A year ago we stopped updating the old registry: https://github.com/hexpm/hexpm/commit/18feda8de16853535ac1d35f66279aab1f75c329. Since we haven't had any reports about users noticing it is no longer updating we can assume it is no longer in active use. We have no plans of deleting the old registry, this patch is only removing the ability to update it.

**Comment by ericmj** [comment]
@wojtekmach Any blockers from the meeting on this or can we merge?

**Comment by wojtekmach** [comment]
no blockers, ship it!

**Pull request merged**
