### PR TITLE
Replace HexpmWeb.ViewHelpers import with an alias

### PR DESCRIPTION
**Pull request by wojtekmach**
To do this I used a small tool I was working on recently, [import2alias.exs](https://gist.github.com/wojtekmach/4e04cbda82ba88af3f84c44ec746b7ca): `mix run import2alias.exs Hexpm.ViewHelpers ViewHelpers`. More info about that soon-ish, I'm planning to write up a blog post about it with some additional background information.

### CODE REVIEW

**Comment by ericmj** [comment]
This is really great. Did you do any benchmarks or tests to see if this improved number or recompiled modules or recompilation time?

**Comment by wojtekmach** [comment]
I sure did, here are the results,

before:

```
src/hexpm[master]% touch lib/hexpm/repository/package.ex && time mix compile
Compiling 114 files (.ex)

real	0m5.111s
user	0m14.431s
sys	0m2.771s
```

after:

```
src/hexpm[wm-aliases]% touch lib/hexpm/repository/package.ex && time mix compile
Compiling 78 files (.ex)

real	0m3.896s
user	0m9.933s
sys	0m1.760s
```

Clearly there's more work to be done, but that's a step in the right direction. We have a similar issue with `import HexpmWeb.ControllerHelpers` but that one is more subtle because we use some of the functions as _function_ plugs, the solution would be to refactor them to _module_ plugs but that's for the future.

**Comment by JMurphyWeb** [comment]
@wojtekmach I have updated your script as it wasn't working in template files for me due to no column data:

https://gist.github.com/JMurphyWeb/f9d4fe263d31de8eb23d5a9a7f315145

**Comment by wojtekmach** [comment]
Thanks for the heads up! The missing column data (for EEx templates, right?) required changes in elixir and they'll be available in v1.11.0.

**Pull request merged**
