### PR TITLE
Fixes 404 page does not show you as logged in

### LINKED ISSUE #651: 404 page does not show you as logged in

### PR DESCRIPTION
**Pull request by pragmaticivan**
fixes #651 

Not sure if that would be the best solution, but works very well.

<a href="https://cl.ly/341e2d1y1G1F" target="_blank"></a>

### CODE REVIEW

**Comment by josevalim** [comment]
It is generally not advisable to perform actions on the error pages, as you are not sure what caused the error in the first place. For example, [GitHub's 404](https://github.com/odsajdlasjdklsakjdamg) does not show any login information as well.

**Comment by ericmj** [comment]
I think @josevalim is right, because even with this change we will not show you as logged in if the 404 was raised in a Plug.Exception since the conn assigns are lost.

**Comment by ericmj** [comment]
I think we should change the error page to something similar to github's. Sorry for misleading you @pragmaticivan.

**Comment by pragmaticivan** [comment]
I agree, what about removing the header (navbar) ?

**Comment by ericmj** [comment]
> I agree, what about removing the header (navbar) ?

We can try that or maybe keeping the header but only show the logo so you have a link back to the start page. Check what you think looks best.

**Comment by pragmaticivan** [comment]
404page

what about that?

**Comment by ericmj** [comment]
Looks great! Thank you.

**Comment by pragmaticivan** [comment]
Closing in favor of https://github.com/hexpm/hexpm/pull/657

**Pull request closed without merging**
