### PR TITLE
snake_case validation for package name

### PR DESCRIPTION
**Pull request by spirinvladimir**
At [issue](https://github.com/hexpm/hex/issues/425) I find useful to have snake_case validation of package name.

This regex extra cover such cases:
❌ my_
❌ my_package_
❌ my__package
✅ my
✅ my_package123
✅ my_package_123

### CODE REVIEW

**Comment by ericmj** [comment]
These packages fails the new regex `["compassIO", "mmExchangeRate", "parabaikElixirConverter", "rabbitElixir", "contextEX", "addressBook"]` so we would need to move the validation to happen only on `:create`.

**Comment by josevalim** [comment]
> ["compassIO", "mmExchangeRate", "parabaikElixirConverter", "rabbitElixir", "contextEX", "addressBook"]

There is nothing wrong with those packages to be fair.

**Comment by ericmj** [comment]
> There is nothing wrong with those packages to be fair.

Technically there is nothing wrong with them but the convention for 99% of the packages is to use snake case so most people would except that and using another casing might lead to confusion if someone does `{:compass_io, ...}` and it doesn't work.

So I guess the question is if it would be more helpful for the community if we enforced a convention.

**Comment by spirinvladimir** [comment]
@ericmj I've moved validation to `:create`.
I'm new to Elixir community. I was trying publish my first package to hex. My mistake was space symbol into package name. This mistake produce error with message _`HTTP status code: 505`_ . I'd like to save time for other developers by adding validation.

**Comment by ericmj** [comment]
@spirinvladimir Just to clarify the validation to check for spaces was already there. The reason you got a 505 error was because of a bug in the client that has been fixed. This PR introduces extra validations that rejects camel case package names in favor of snake case, we are currently discussing in the core team if we should add this validation.

**Comment by spirinvladimir** [comment]
@ericmj You are completely right.

**Comment by ericmj** [comment]
Thanks for the PR and raising the issue. We have decided to not go ahead with snake case validation since we already have packages with other casings and they are valid as @josevalim.

**Pull request closed without merging**
