### PR TITLE
Styling Login Page

### PR DESCRIPTION
**Pull request by TraceyOnim**

### CODE REVIEW

**Comment by ericmj** [comment]
Looks great so far 👍

**Comment by TraceyOnim** [comment]
> Looks great so far +1

Thank you :smiley:

**Review by ericmj — COMMENTED** [review]
This looks really great I just have a few minor comments.

The show/hide password icon is offset too much to the left:
Screenshot 2021-11-18 at 12 34 58

The navbar also looks slightly offset and too narrow. But this might be because the missing CSS from the footer. It might be good to the footer next to ensure it doesn't mess with other designs.

Screenshot 2021-11-18 at 12 35 36

The page background should be `#E5E5E5`.

The color on the login button is slightly off, I think you need to add the color palette from figma [1] to tailwind [2].

[1] https://www.figma.com/file/XRIdYl3S67mMjzxBV6CnO2/hex.pm-Design-System?node-id=61%3A0
[2] https://tailwindcss.com/docs/customizing-colors#custom-colors

**Comment by TraceyOnim** [comment]
> This looks really great I just have a few minor comments.
> 
> The show/hide password icon is offset too much to the left: Screenshot 2021-11-18 at 12 34 58
> 
> The navbar also looks slightly offset and too narrow. But this might be because the missing CSS from the footer. It might be good to the footer next to ensure it doesn't mess with other designs.
> 
> Screenshot 2021-11-18 at 12 35 36
> 
> The page background should be `#E5E5E5`.
> 
> The color on the login button is slightly off, I think you need to add the color palette from figma [1] to tailwind [2].
> 
> [1] https://www.figma.com/file/XRIdYl3S67mMjzxBV6CnO2/hex.pm-Design-System?node-id=61%3A0 [2] https://tailwindcss.com/docs/customizing-colors#custom-colors

Thank you!  working on them

**Comment by ericmj** [comment]
Great stuff Tracey. Thank you!

**Pull request merged**
