### PR TITLE
add styling to pricing page

### PR DESCRIPTION
**Pull request by TraceyOnim**

### CODE REVIEW

**Comment by ericmj** [comment]
Looks really good. Only two comments. The box for each tier should have rounded edges and are missing their border. The FAQ should have more padding to the left and right, it is almost out to the edges now. Can you make it only slightly wider than the three boxes, like in the figma design?

**Comment by ericmj** [comment]
The FAQ should also go to the bottom of the page so it touches the footer. Sorry if I was unclear about this earlier.

**Comment by TraceyOnim** [comment]
> The FAQ should also go to the bottom of the page so it touches the footer. Sorry if I was unclear about this earlier.

Working on it

**Comment by TraceyOnim** [comment]
> Looks really good. Only two comments. The box for each tier should have rounded edges and are missing their border. The FAQ should have more padding to the left and right, it is almost out to the edges now. Can you make it only slightly wider than the three boxes, like in the figma design?

Thank you! Working on it

**Pull request merged**
