### PR TITLE
Expire etags due to API shape change

### PR DESCRIPTION
**Pull request by wojtekmach**
We've added `html_url` to payload, however due to caching it's not gonna be seen until next packages publish. Here, we add a way to quickly expire cache.

### CODE REVIEW

**Comment by ericmj** [comment]
Maybe we should do git ref or something like that so we don't have to remember to manually bust? Another idea is to actually build the view and get the md5 of that?

**Comment by wojtekmach** [comment]
> Maybe we should do git ref or something like that

could you elaborate?

> Another idea is to actually build the view and get the md5 of that?

a disadvantage is we'd need to hit the DB to build the view. Not sure yet how it would look in practice (worried a bit about making the controllers more complicated) but I'll investigate.

another (crazy) idea is to have a compile-time thing that assentially does `cat views/*.ex | md5`

**Comment by ericmj** [comment]
> could you elaborate?

Instead of always updating `:v2 -> :v3` we could encode the sha for the current git commit.

> a disadvantage is we'd need to hit the DB to build the view. Not sure yet how it would look in practice (worried a bit about making the controllers more complicated) but I'll investigate.

We already hit the db to get the structs, so I was thinking calling the view without rendering would be pretty cheap in comparison.

**Comment by wojtekmach** [comment]
doh, that makes sense, I'll look into these

**Comment by wojtekmach** [comment]
I'm gonna reopen when I have working code

**Pull request closed without merging**
