### PR TITLE
Exact match with spaces

### PR DESCRIPTION
**Pull request by adamwight**
Normalize the search term so that spaces are translated to underscores,
before checking for an exact match.

FIXME: Fails to render the match because the main package_count filter
returns 0 and exact matches are nested within that clause.  I would
suggest making the exact match and other package results independent, so
the algorithms can diverge.

### CODE REVIEW

**Comment by ericmj** [comment]
> I would suggest making the exact match and other package results independent, so the algorithms can diverge.

👍

**Comment by ericmj** [comment]
@adamwight Did you want to add a test as well?

**Comment by adamwight** [comment]
> Did you want to add a test as well?

Thanks for the nudge!  Yes, I'll give that a try.

**Comment by adamwight** [comment]
Now includes basic tests.

This could be split into a new issue, but what do you think about the redundant result where the exact match also shows up in the main search results?  Removing the duplicate would definitely improve the results page in a case like, https://hex.pm/packages?search=logger_file_backend_win .

And maybe the exact match result should include the release version number like the main results do?

**Comment by ericmj** [comment]
If we only have one result we could skip showing main results.

> And maybe the exact match result should include the release version number like the main results do?

👍

**Pull request merged**
